Ts rebuild
DGGua/LuckyFrontEnd pull request #23
Opened 2022-08-14 12:52 UTC by gbnijnugyf

style：Ts

2022-08-14 16:53 UTC, DGGua requested changes

2022-08-14 16:53 UTC, DGGua commented on src/config/Global.tsx
> +export interface Iobject{
大驼峰 改为 IObject

2022-08-14 16:53 UTC, DGGua commented on src/pages/Login/loginSchools.tsx
> +    onClick:React.MouseEventHandler<HTMLDivElement> | undefined,
直接改成 onClick?: ReactMousebalabaa
不需要后面那个undefined

2022-08-15 06:50 UTC, DGGua commented on src/pages/MyWish/index.tsx
> +  type: number,
写成具体数字

2022-08-15 06:57 UTC, DGGua requested changes

2022-08-15 06:57 UTC, DGGua commented on src/components/Header/index.tsx
> +          onClick={() => title === "标签页" ? null : handleBack}
本身不是函数，不要修改

2022-08-15 06:57 UTC, DGGua commented on src/components/Button/index.tsx
> +    onClick:()=>void,
类型问题

2022-08-15 06:57 UTC, DGGua commented on src/components/Button/index.tsx
> +    children:string|any
类型问题

2022-08-15 06:57 UTC, DGGua commented on src/components/Button/index.tsx
> +    children:string|any
类型问题

2022-08-15 06:57 UTC, DGGua commented on src/components/Button/index.tsx
> +    style:{[key:string]:string},
类型问题

2022-08-15 06:57 UTC, DGGua commented on src/components/Button/index.tsx
> +    onClick:()=>void,
类型问题

2022-08-15 06:57 UTC, DGGua commented on src/components/Header/index.tsx
> +export interface IgetTitle {
类型不对吧

2022-08-15 06:57 UTC, DGGua commented on src/pages/MyWish/index.tsx
> +  const sortWishes = (oldwishes:Array<IwishObject>) => {
大驼峰

2022-08-16 07:25 UTC, DGGua requested changes

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                    props.wish.school === '0' ? '华小师' : '武小理'}</p>
school是number不是string

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                    props.wish.school === '0' ? '华小师' : '武小理'}</p>
另外，用常量，不要用魔法数字

2022-08-16 07:25 UTC, DGGua commented on src/common/service.ts
> +function IsToken(props : _config):_config {
大驼峰

2022-08-16 07:25 UTC, DGGua commented on src/common/service.ts
> +        message?: string
单独建interface

2022-08-16 07:25 UTC, DGGua commented on src/components/ConfirmPanel/index.jsx
> +//ts暂时没改好，测试用jsx
文件待删

2022-08-16 07:25 UTC, DGGua commented on src/components/ConfirmPanel/index.jsx
> +//ts暂时没改好，测试用jsx
待修改（

2022-08-16 07:25 UTC, DGGua commented on src/common/service.ts
> +    if (response.statusText === 'OK') {
之前提过的问题，逻辑不对，能拿到返回值均为OK

2022-08-16 07:25 UTC, DGGua commented on src/common/service.ts
> +    else if (response.data.status !== 0) {
这个地方的代码应该永远不会出现，测试一下

2022-08-16 07:25 UTC, DGGua commented on src/common/service.ts
> +    data: any,  //IsToken中需要加入token属性
data不要写any，用<T>设定模板类型

2022-08-16 07:25 UTC, DGGua commented on src/common/service.ts
> +    data: URL,
为什么data是URL

2022-08-16 07:25 UTC, DGGua commented on src/common/service.ts
> +        message?: string
data抽象出来，抽象成<T>

2022-08-16 07:25 UTC, DGGua commented on src/common/service.ts
> +    if (props.url && props.data && props.method) {
你这逻辑不太对吧，有的请求确实没有data，那如果url和method正常，那照样拿不到数据

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                        alert(res.msg) //类型“AxiosResponse<any, any>”上不存在属性“msg” ,res暂时定义为any
确实不存在啊，是res.data.msg

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                Service.lightWishOn(id, name, tel, qq, wechat).then((res:any) => {
no any

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                let id = wishes[0].wish_id as string
no as    
wish_id为什么是string

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +            if (wishes[0].wish_id !== undefined) {
如果是undefined会怎么样

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +    const onTouchMove = (e: any) => {//e:ChangeEvent<HTMLDivElement>替换为any，targeTouches类型未知
no any

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +    const onTouchStart = (e: any) => {  //e:ChangeEvent<HTMLDivElement>替换为any，targeTouches类型未知
no any

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +export interface IWishItemProps_ {
起名不要最后下划线，为什么不取成IWishItemProps

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +export interface IWishesObject {
这个需要export吗，还有下面的interface
如果是某些页面共用的话，建议单独放在公共文件中

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +export interface IonTouchStart_e {
什么取名规范

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +export interface IHTMLonTouchStartElemmt extends HTMLElement {
empty

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +const WishItem = (props: IWishItemProps_) => {
组件统一写成 function WIshItem(props: IWishItemProps){} 的格式吧

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                    props.wish.school.toString() === '0' ? '华小师' : '武小理'}</p>
为什么非要绕一圈先toString再和字符串比较

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                    props.wish.school.toString() === '0' ? '华小师' : '武小理'}</p>
而且逻辑不明

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +    start: any, //touch.pageX和e.targetTouches[0]不知道是啥类型，详见130，131
再找找

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +    start: any, //touch.pageX和e.targetTouches[0]不知道是啥类型，详见130，131
之前的代码不一定对，可以考虑其他实现方法

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +    const category = (useLocation().state as ILocationState).category as number;
why as

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +        Service.getWishByCategories(category.toString()).then((res) => {
why to string

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                let wish = { wish: "当前分类没有愿望哦~", school: -1, wishman_name: "" }
MAGIC NUMBER

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +        { wish: "当前分类没有愿望哦~", school: -1, wishman_name: "" }
magic number

2022-08-16 07:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +    onTouchStart?: (e: any) => void,
no any

2022-08-16 07:25 UTC, DGGua commented on src/pages/MyWish/list.tsx
> +    onClick:React.MouseEventHandler<HTMLLIElement> | undefined,
"| undefined"  ==> "onClick?:"

2022-08-16 07:25 UTC, DGGua commented on src/pages/MyWish/list.tsx
> +
"wish => {return ..}"  ==> "wish => ..."

2022-08-16 07:25 UTC, DGGua commented on src/pages/Send/index.tsx
> +            Service.postWish(nameValue, QQ, wechat, tel, wishContent, category.toString())
why to string

2022-08-16 07:25 UTC, DGGua commented on src/pages/MyWish/index.tsx
> +    Service.getUserWishPost().then((res: AxiosResponse<any, any>) => {
no any
而且这种地方你不需要声明类型，会自动提取的

2022-08-16 07:25 UTC, DGGua commented on src/pages/MyWish/index.tsx
> +    Service.getUserWishLight().then((res: AxiosResponse<any, any>) => {
no any
而且这种地方你不需要声明类型，会自动提取的

2022-08-16 07:25 UTC, DGGua commented on src/config/Global.tsx
> +export interface IObject{
命名规范，写清楚是干什么的，不要起一个笼统的Object

2022-08-16 07:25 UTC, DGGua commented on src/common/service.ts
> +        return axios.delete(BASEURL + `/wishes?wish_id=${wish_id}`, axiosProp2)
这个为什么不走global

2022-08-22 13:00 UTC, DGGua requested changes

2022-08-22 13:00 UTC, DGGua commented on src/components/Header/index.tsx
> +interface ItitleList {
ITitleList

2022-08-22 13:00 UTC, DGGua commented on src/index.tsx
> +const container = document.getElementById('root') as HTMLElement;
no as 
if(! container)return;
// 后面的代码

2022-08-22 13:00 UTC, DGGua commented on src/pages/Home/index.tsx
> +    navigate(`/wishpool/wish/:${tag.enName}`, { state: { category: tag.category } });
你确定要加冒号？

2022-08-22 13:00 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                    mystyle={{
要么还叫style，要么小驼峰改成myStyle

2022-08-22 13:00 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                        alert(res.data.msg) //类型“AxiosResponse<any, any>”上不存在属性“msg” ,res暂时定义为any
那你为什么不把any改掉呢

2022-08-22 13:00 UTC, DGGua commented on src/common/service.ts
> +interface light_information {
命名规范呢？？？？？

2022-08-22 13:00 UTC, DGGua commented on src/common/service.ts
> +export interface wishMan_information{
命名规范呢？？？

2022-08-22 13:00 UTC, DGGua commented on src/common/service.ts
> +        message?: string
类型提出来

2022-08-22 13:00 UTC, DGGua commented on src/pages/MyWish/index.tsx
> +  const [wishPost, setWishPost] = useState(wishPost_init);
常量全大写

2022-08-22 14:36 UTC, gbnijnugyf commented on src/pages/Wishes/index.tsx
> +                let id = wishes[0].wish_id as string
等接口

2022-08-23 15:03 UTC, DGGua approved these changes

2022-08-23 15:03 UTC, DGGua commented on src/common/service.ts
> +interface IlightInformation {
ILight?

2022-08-23 15:03 UTC, merged