Whut login register
DGGua/LuckyFrontEnd pull request #59
Opened 2022-09-12 05:29 UTC by gbnijnugyf

2022-09-14 04:25 UTC, DGGua requested changes

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  null = 0,
和下面命名规则相同也叫`初始化`吧

是不是叫`初始化`不太好？要不要改名`未定义`

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  postWish_2(
命名规范，下同

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  achieveWish_2(id: string) {
命名规范，下同

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  get_lightedWishInfo() {
命名规范，下同

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  get_postedWishInfo() {
命名规范，下同

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  getWishByCategories_2(categories: string) {
命名规范，下同

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  getWishDetail_2(id: string) {
命名规范，下同

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  deleteWish_2(desire_id: string) {
命名规范，下同

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  // },
注释删除

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  // },
注释删除

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +  // },
注释删除

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +// };
注释删除

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +          })} */}
这个究竟是什么问题，想办法改回foreach形式

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +          console.log(e.target); // props.onChangeState = (e.target.value);
log删除

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +          props.onChangeState = e.target.value;
不要这样改！有问题！

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +        onClick={() => (props.value = undefined)}
不要这样改！有问题！

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +        defaultValue={props.value ? props.value : undefined}
这要排除什么情况？为什么默认值是undefined？  将整个修改为` defaultValue={props.value || ""}`

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +    await Service.getManInfo("-1").then((res) => {
-1 magic value

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +      console.log("试图跳转");
删掉log

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +      console.log("试图关闭弹窗");
删掉log

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +    // const [tel, setTel] = useState("");
删掉没用注释

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +    let Info = {
命名规范

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +        console.log("试图关闭弹窗1");
删掉log

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +        console.log("试图关闭弹窗2");
log

2022-09-14 04:25 UTC, DGGua commented on src/pages/Detail/WishDetail.tsx
> +    if (wish.state === 0 && isMine /*1*/) {
注释什么意思写清楚，如果是测试用的删掉

2022-09-14 04:25 UTC, DGGua commented on src/pages/Login/index.tsx
> +  //   )}&continueurl=${encodeURIComponent(continueurl)}`;
删掉

2022-09-14 04:25 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +// const SCHOOLINIT: 0 | 1 | 2 = 0;
删掉

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +export interface IWishInfo_withName {
命名规范

2022-09-14 04:25 UTC, DGGua commented on src/pages/MyWish/list.tsx
>    let wish_state = useLocation().state as IWishState;
命名规范

2022-09-14 04:25 UTC, DGGua commented on src/pages/Register/index.tsx
> +        console.log(WhutEVV);
删掉

2022-09-14 04:25 UTC, DGGua commented on src/pages/Register/index.tsx
> +        console.log(WhutEVV);
删掉

2022-09-14 04:25 UTC, DGGua commented on src/common/service.ts
> +export enum Type {
不要只写个`Type`，写清楚是什么tpye，比如WishCategories之类的起名

2022-09-14 04:25 UTC, DGGua commented on src/pages/Send/index.tsx
> +      Service.getManInfo("-1").then((res)=>{
magic value

2022-09-15 01:37 UTC, DGGua requested changes

2022-09-15 01:37 UTC, DGGua commented on src/common/service.ts
> +// import { IWishObject } from "../pages/MyWish";
这种就不要这样注释了，直接删掉就行

以后你要是会再用到，vscode会自动import的

2022-09-15 01:37 UTC, DGGua commented on src/common/service.ts
> +    school:School//0错误or初始化、1武理、2华师
格式化有问题，是不是prettier

2022-09-15 01:37 UTC, DGGua commented on src/common/service.ts
> +  //（new）获取用户的信息111
这些111是什么意思

2022-09-15 01:37 UTC, DGGua commented on src/components/ConfirmPanel/index.tsx
> +          <div className="confirmFalse" onClick={()=>{props.action.no()}}>
怎么变回旧的了？？？？

2022-09-15 01:37 UTC, DGGua commented on src/pages/MyWish/index.tsx
> +
注释删掉

2022-09-15 01:37 UTC, DGGua commented on src/pages/Detail/index.tsx
> +      </ConfirmPanel> */}
注释删掉

2022-09-15 01:37 UTC, DGGua commented on src/pages/Detail/index.tsx
> +
注释删掉

2022-09-15 01:37 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +};
旧的？

2022-09-15 01:37 UTC, DGGua commented on src/common/service.ts
> +        Email: email,
？为什么会出现大写？

2022-09-18 01:39 UTC, DGGua requested changes

2022-09-18 01:39 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +  wish: IWishInfo_withName;
命名规范

2022-09-18 07:02 UTC, gbnijnugyf commented on src/pages/Detail/DetailPage.tsx
> +          })} */}
改回一开始的html了

2022-09-18 07:05 UTC, gbnijnugyf commented on src/pages/Send/index.tsx
> +      Service.getManInfo("-1").then((res)=>{
后端约定，查询用户自身信息

2022-09-18 07:06 UTC, gbnijnugyf commented on src/common/service.ts
> +  //（new）获取用户的信息111
测试通过

2022-09-18 07:07 UTC, gbnijnugyf commented on src/common/service.ts
> +        Email: email,
对应后端字段名

2022-09-18 08:03 UTC, DGGua submitted a review, later dismissed

2022-09-18 08:07 UTC, DGGua approved these changes

2022-09-18 08:09 UTC, merged