UI refactor
DGGua/LuckyFrontEnd pull request #67
Opened 2022-09-25 09:54 UTC by gbnijnugyf

2022-09-25 10:53 UTC, gbnijnugyf commented
1. logo居中问题
2. 三个点下的“规则”字样
3. 适配问题

2022-09-26 05:44 UTC, DGGua commented
**提 issue**

2022-09-26 06:24 UTC, DGGua requested changes

2022-09-26 06:24 UTC, DGGua commented on src/components/Button/index.scss
>    text-align: center;
你这样写会导致 **全局** 居中。
如果你真的想这样，不要把这种全局性的东西放在这种地方，写个global.scss

2022-09-26 06:24 UTC, DGGua commented on src/components/Button/index.scss
> +  }
你这是**通用组件**，不要把定制化的东西写在组件里

2022-09-26 06:24 UTC, DGGua commented on src/components/Header/index.tsx
> +// };
删掉

2022-09-26 06:24 UTC, DGGua commented on src/components/Header/index.tsx
> +  // };
删掉

2022-09-26 06:24 UTC, DGGua commented on src/components/Header/index.tsx
> +          /> */}
删掉？

2022-09-26 06:24 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +
删掉？

2022-09-26 06:24 UTC, DGGua commented on src/pages/Detail/DetailPage.tsx
> +    // console.log(props.wish.state, isMine, achieved)
删掉？

2022-09-26 06:24 UTC, DGGua commented on src/components/Header/index.scss
> +      // }
删掉？

2022-09-26 06:24 UTC, DGGua commented on src/pages/Detail/WishDetail.tsx
> +      {getForward()}
我没叫你改成标签形式吗

2022-09-26 06:24 UTC, DGGua commented on src/pages/Detail/index.scss
> +        //     white 31px);
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Detail/index.tsx
> +      if (res.data.status === -1) {//查询不到该愿望//与后端约定为-1
enum

2022-09-26 06:24 UTC, DGGua commented on src/pages/Detail/notfound.tsx
> +    {/* <div className="nav">5s后自动跳转</div> */}
5s还是3s？

2022-09-26 06:24 UTC, DGGua commented on src/pages/Home/index.tsx
> +// import noteBook from "../../static/images/noteBook.png"
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Home/index.tsx
>          onClick={() => goSend()} //此处goSend函数参数删去tags，因为不知道有啥用（也不需要参数）。。
onClick ={goSend}

2022-09-26 06:24 UTC, DGGua commented on src/pages/Home/index.tsx
> +        style={{ marginTop: "10%" }}
为什么不写到css去

2022-09-26 06:24 UTC, DGGua commented on src/pages/Home/index.tsx
>            return (
不加大括号就不用写return

2022-09-26 06:24 UTC, DGGua commented on src/pages/Login/WhutLogin.tsx
> +                    {"确定"}
？

2022-09-26 06:24 UTC, DGGua commented on src/pages/Login/index.scss
> +// }
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Login/index.scss
> +    // background-position-y: 1.25em;
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Login/loginSchools.tsx
> +          {"完成"}
？

2022-09-26 06:24 UTC, DGGua commented on src/utils/router.tsx
> +            {/* <Route path="index" element={<Index />} /> */}
删掉

2022-09-26 06:24 UTC, DGGua commented on src/utils/router.tsx
> +      {/* {location.pathname.match(/login/) ? null : <Header></Header>} */}
删掉

2022-09-26 06:24 UTC, DGGua commented on src/utils/router.tsx
> +// import { Index } from "../pages/MyWish/index";
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +                ? props.wish.view_user.name.charAt(0) + "同学"
这种点点点你不累吗。。。解构一下

2022-09-26 06:24 UTC, DGGua commented on src/pages/Wishes/index.tsx
> +      {/* <img src={wishItem} className="wish-img" alt="" /> */}
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Wishes/index.scss
> +      // padding-top: 5em;
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Wishes/index.scss
> +      &2{
？这是什么东西？

2022-09-26 06:24 UTC, DGGua commented on src/pages/Wishes/index.scss
> +    // height: 14em;
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Send/index.tsx
> +                {/* <img src={paperplane} alt="" style={{ paddingBottom: "0.2em" }} />{" "} */}
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Send/index.tsx
> +              // style={{ background: "white", color: "#f25125", margin: "0.5em 0" }}
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Register/index.tsx
> +      {/* <ButtonL onClick={props.onClick}>{props.btnText}</ButtonL> */}
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Send/index.scss
> +// }
？？？？？？？？？？？？？？？

2022-09-26 06:24 UTC, DGGua commented on src/pages/Send/index.scss
> +      // outline: none;
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Register/index.scss
> +        // color        : #577DAB;
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/Register/index.scss
>      // align-items    : center;
删掉

2022-09-26 06:24 UTC, DGGua commented on src/pages/MyWish/list.tsx
> +  // const wishLight = wishState.wishLight;
删掉？

2022-09-26 06:24 UTC, DGGua commented on src/pages/MyWish/list.tsx
> +  //以上为index导入--to合并两个文件
你index都没了写这个有啥用

2022-09-26 06:24 UTC, DGGua commented on src/pages/MyWish/index.scss
> +    background-image: url("../../static/images/wishItemPink.png");
你   有没有想过  这些图片  差别只在背景颜色上  只需要改 background-color就行

2022-09-28 08:54 UTC, DGGua approved these changes, later dismissed

2022-09-28 10:21 UTC, DGGua approved these changes

2022-09-28 10:23 UTC, merged